-- =============================================
-- 🧠 SAFETRIP PRO - SUPABASE DATABASE SETUP
-- =============================================
-- Copy and paste this entrie script into your Supabase SQL Editor to create the necessary tables.

-- 1️⃣ Enable UUID extension (usually enabled by default, but good to ensure)
create extension if not exists "uuid-ossp";

-- =============================================
-- 2️⃣ TRIPS TABLE
-- Stores trip summary data (Start/End time, Distance, Score)
-- =============================================
create table public.trips (
  id uuid default uuid_generate_v4() primary key,
  user_id text, -- link to auth.users if using Supabase Auth, or just a string ID
  start_time timestamp with time zone default timezone('utc'::text, now()),
  end_time timestamp with time zone,
  start_location text,
  end_location text,
  distance_km numeric,
  duration_sec numeric,
  alert_count integer default 0,
  safety_score integer, -- 0 to 100
  status text check (status in ('active', 'completed', 'cancelled')) default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS) - Optional for now, but recommended
alter table public.trips enable row level security;

-- Allow public access for development (Replace with stricter policies for production)
create policy "Allow public access to trips"
on public.trips for all using (true);

-- =============================================
-- 3️⃣ HAZARD REPORTS TABLE
-- Stores user-submitted reports (Accident, Traffic, Weather)
-- =============================================
create table public.hazard_reports (
  id uuid default uuid_generate_v4() primary key,
  user_id text,
  type text, -- 'Accident', 'Traffic', 'Weather', 'Road Block'
  severity text check (severity in ('low', 'medium', 'high')),
  location text, -- simple string coordinates "lat, long"
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.hazard_reports enable row level security;

-- Allow public access
create policy "Allow public access to hazard_reports"
on public.hazard_reports for all using (true);

-- =============================================
-- 4️⃣ LOCATION HISTORY TABLE (Optional)
-- Stores individual GPS points for heatmaps/playback
-- Warning: Can grow very large!
-- =============================================
create table public.location_history (
  id bigint generated by default as identity primary key,
  user_id text,
  latitude double precision,
  longitude double precision,
  speed double precision, -- km/h
  timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.location_history enable row level security;

-- Allow public access
create policy "Allow public access to location_history"
on public.location_history for all using (true);
-- =============================================
-- 5️⃣ EMERGENCY CONTACTS TABLE
-- Stores contacts to be alerted during SOS
-- =============================================
create table public.emergency_contacts (
  id uuid default uuid_generate_v4() primary key,
  user_id text not null,
  name text not null,
  phone text not null,
  relation text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.emergency_contacts enable row level security;
create policy "Allow public access to emergency_contacts" on public.emergency_contacts for all using (true);
